# Generated by Django 4.0.5 on 2022-06-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rango',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='../images/icons')),
            ],
        ),
    ]
