# Generated by Django 4.0.5 on 2022-06-09 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='insignia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='../images/icons')),
            ],
            options={
                'verbose_name': 'insignia',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='rango',
            options={'ordering': ['name'], 'verbose_name': 'rango'},
        ),
        migrations.CreateModel(
            name='reward',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('puntos', models.IntegerField()),
                ('image', models.ImageField(upload_to='../images/reward')),
                ('rango', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points.rango')),
            ],
            options={
                'verbose_name': 'reward',
                'ordering': ['name'],
            },
        ),
    ]
