# Generated by Django 4.0.5 on 2022-06-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_remove_event_creator_remove_event_date_event_date_and_more'),
        ('user', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='event',
            field=models.ManyToManyField(blank=True, null=True, to='event.event'),
        ),
    ]
